# schema.yml

version: 2

sources:
    - name: staging
      database: crafty-elf-376416
      schema: trips_data_all_us

      tables:
          - name: green_tripdata
          - name: yellow_tripdata
